[tox]
envlist =
    py3.10,py3.11,py3.12,py3.13,py3.14,,pypy3.11,
    coverage,
    lint,
    docs

isolated_build = true

[testenv]
use_develop = true
deps =
    pytest
    pytest-cov
commands =
    python --version
    python -mpytest {posargs:}
setenv =
    COVERAGE_FILE=.coverage.{envname}

[testenv:coverage]
skip_install = true
basepython =
    python3.14
commands =
    coverage combine
    coverage report --fail-under=100 --show-missing
    coverage xml
deps =
    coverage
setenv =
    COVERAGE_FILE=.coverage
depends = py3.10,py3.14

# we separate coverage into its own testenv because a) "last run wins" wrt
# cobertura jenkins reporting and b) pypy and jython can't handle any
# combination of versions of coverage and nosexcover that i can find.

[testenv:docs]
basepython =
    python3.14
commands =
    sphinx-build -b html -d docs/_build/doctrees docs docs/_build/html
    sphinx-build -b doctest -d docs/_build/doctrees docs docs/_build/doctest
deps =
    Sphinx

[testenv:lint]
skip_install = true
commands =
    ruff check
    ruff format --check
    check-manifest
   # build sdist/wheel
   python -m build .
   twine check dist/*
dependency_groups =
    dev
